version: '3'

services:
  php:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: php-snaplink
    restart: unless-stopped
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgresql-application-snaplink
      - DB_DATABASE=application
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/var/www/application/
    working_dir: /var/www/application/
    networks:
      - backend-snaplink
  composer:
    image: composer:1.8
    volumes:
      - .:/var/www/application/
    container_name: composer-snaplink
    working_dir: /var/www/application/
    command: install

networks:
  backend-snaplink:
    driver: bridge
